import { GHClasses, GloomhavenItem, GloomhavenItemSlot, SpecialUnlockTypes } from "../../State";
import { Expansions, GameType } from "../GameType";

export const items: GloomhavenItem[] = [
	{
		name: "Boots of Striding",
		id: 1,
		cost: 20,
		count: 2,
		slot: GloomhavenItemSlot.Legs,
		source: "Prosperity 1",
		spent: true,
		desc: "During your movement, add +2 Move ^move^ to the movement.",
		faq: "Boots of Striding only add to the numerical value of an existing single movement ability. They do not give you a free movement action.",
		unlockProsperity: 1,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 1,
		imageNumber: 0,
	},
	{
		id: 2,
		name: "Winged Shoes",
		cost: 20,
		count: 2,
		slot: GloomhavenItemSlot.Legs,
		source: "Prosperity 1",
		spent: true,
		desc: "During your movement, add Jump ^jump^ to the movement.",
		faq: "Winged Shoes may be used for only a single movement ability, not for multiple movement abilities of an action (ex: Action with Move, Attack, Move).",
		unlockProsperity: 1,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 1,
		imageNumber: 2,
	},
	{
		id: 3,
		name: "Hide Armor",
		cost: 10,
		count: 2,
		slot: GloomhavenItemSlot.Body,
		source: "Prosperity 1",
		spent: true,
		minusOneCardsAdded: 2,
		useSlots: 2,
		desc: "On the next two sources of damage to you from attacks, gain Shield ^shield^ 1.",
		faq: "Hide Armor only grants the shield for the attack, not until the end of the round.",
		unlockProsperity: 1,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 1,
		imageNumber: 4,
	},
	{
		id: 4,
		name: "Leather Armor",
		cost: 20,
		count: 2,
		slot: GloomhavenItemSlot.Body,
		source: "Prosperity 1",
		spent: true,
		desc: "When attacked, the attacker gains Disadvantage on the attack.",
		faq: "The Leather Armor must be used before the enemy draws an attack modifier card.",
		unlockProsperity: 1,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 1,
		imageNumber: 6,
	},
	{
		id: 5,
		name: "Cloak of Invisibility",
		cost: 20,
		count: 2,
		slot: GloomhavenItemSlot.Body,
		source: "Prosperity 1",
		consumed: true,
		desc: "During your turn, gain INVISIBLE $invisible$.",
		unlockProsperity: 1,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 1,
		imageNumber: 8,
	},
	{
		id: 6,
		name: "Eagle-Eye Goggles",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.Head,
		source: "Prosperity 1",
		spent: true,
		desc: "During your attack, gain Advantage on the entire Attack action.",
		unlockProsperity: 1,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 1,
		imageNumber: 10,
	},
	{
		id: 7,
		name: "Iron Helmet",
		count: 2,
		cost: 10,
		slot: GloomhavenItemSlot.Head,
		source: "Prosperity 1",
		desc: "When attacked, consider any ^modifier_2x_circle^ attack modifier card the enemy draws to be a ^modifier_zero_circle^ instead.",
		unlockProsperity: 1,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 1,
		imageNumber: 12,
	},
	{
		id: 8,
		name: "Heater Shield",
		count: 2,
		cost: 20,
		slot: GloomhavenItemSlot.OneHand,
		source: "Prosperity 1",
		spent: true,
		desc: "When damaged by an attack, gain Shield ^shield^ 1 for the attack.",
		unlockProsperity: 1,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 1,
		imageNumber: 14,
	},
	{
		id: 9,
		name: "Piercing Bow",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Prosperity 1",
		consumed: true,
		desc: "During your ranged attack, ignore all Shield values for the entire Attack action.",
		unlockProsperity: 1,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 1,
		imageNumber: 16,
	},
	{
		id: 10,
		name: "War Hammer",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Prosperity 1",
		consumed: true,
		desc: "During your melee attack, add STUN $stun$ to the entire Attack action.",
		unlockProsperity: 1,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 1,
		imageNumber: 18,
	},
	{
		id: 11,
		name: "Poison Dagger",
		count: 2,
		cost: 20,
		slot: GloomhavenItemSlot.OneHand,
		source: "Prosperity 1",
		spent: true,
		desc: "During your melee attack, add POISON $poison$ to a single attack.",
		unlockProsperity: 1,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 1,
		imageNumber: 20,
	},
	{
		id: 12,
		name: "Minor Healing Potion",
		count: 4,
		cost: 10,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 1",
		consumed: true,
		desc: "During your turn, perform a \"Heal ^heal^ 3, self\" action.",
		unlockProsperity: 1,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 1,
		imageNumber: 22,
	},
	{
		id: 13,
		name: "Minor Stamina Potion",
		count: 4,
		cost: 10,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 1",
		consumed: true,
		desc: "During your turn, Recover ^recover^ up to two of your discarded cards.",
		faq: "[Errata] The item should allow you to recover only one discarded card. This is change in an upcoming expansion but may be used for the base game.",
		unlockProsperity: 1,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 1,
		imageNumber: 26,
	},
	{
		id: 14,
		name: "Minor Power Potion",
		count: 4,
		cost: 10,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 1",
		consumed: true,
		desc: "During your attack, add +1 Attack ^attack^ to your entire Attack action.",
		unlockProsperity: 1,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 1,
		imageNumber: 30,
	},
	{
		id: 15,
		name: "Boots of Speed",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.Legs,
		source: "Prosperity 2",
		spent: true,
		desc: "At the beginning of a round, after all ability cards have been revealed, increase or decrease your leading initiative value by 10.",
		unlockProsperity: 2,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 2,
		imageNumber: 0,
	},
	{
		id: 16,
		name: "Cloak of Pockets",
		count: 2,
		cost: 20,
		slot: GloomhavenItemSlot.Body,
		source: "Prosperity 2",
		desc: "You can carry two additional #small# items.",
		unlockProsperity: 2,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 2,
		imageNumber: 2,
	},
	{
		id: 17,
		name: "Empowering Talisman",
		count: 2,
		cost: 45,
		slot: GloomhavenItemSlot.Head,
		source: "Prosperity 2",
		consumed: true,
		desc: "During your turn, Refresh ^refresh^ one of your consumed #small# items.",
		unlockProsperity: 2,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 2,
		imageNumber: 4,
	},
	{
		id: 18,
		name: "Battle-Axe",
		count: 2,
		cost: 20,
		slot: GloomhavenItemSlot.OneHand,
		source: "Prosperity 2",
		consumed: true,
		desc: "During your single-target melee attack action, turn the attack into the following: *cone_0_1*",
		unlockProsperity: 2,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 2,
		imageNumber: 6,
	},
	{
		id: 19,
		name: "Weighted Net",
		count: 2,
		cost: 20,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Prosperity 2",
		spent: true,
		desc: "During your ranged attack, add IMMOBILIZE $immobilize$ to a single attack.",
		unlockProsperity: 2,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 2,
		imageNumber: 8,
	},
	{
		id: 20,
		name: "Minor Mana Potion",
		count: 4,
		cost: 10,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 2",
		consumed: true,
		desc: "During your turn, create any element. @any@",
		unlockProsperity: 2,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 2,
		imageNumber: 10,
	},
	{
		id: 21,
		name: "Stun Powder",
		count: 2,
		cost: 20,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 2",
		consumed: true,
		desc: "During your attack, add STUN $stun$ to a single attack.",
		unlockProsperity: 2,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 2,
		imageNumber: 14,
	},
	{
		id: 22,
		name: "Heavy Greaves",
		count: 2,
		cost: 20,
		slot: GloomhavenItemSlot.Legs,
		source: "Prosperity 3",
		minusOneCardsAdded: 1,
		desc: "You are immune to all forced movement caused by enemies or scenario effects.",
		unlockProsperity: 3,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 3,
		imageNumber: 0,
	},
	{
		id: 23,
		name: "Chainmail",
		count: 2,
		cost: 20,
		slot: GloomhavenItemSlot.Body,
		source: "Prosperity 3",
		minusOneCardsAdded: 3,
		spent: true,
		desc: "On the next three sources of damage to you from attacks, gain Shield ^shield^ 1.",
		faq: "Chainmail only grants the shield for the attack, not until the end of the round.",
		unlockProsperity: 3,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 3,
		imageNumber: 2,
	},
	{
		id: 24,
		name: "Amulet of Life",
		count: 2,
		cost: 20,
		slot: GloomhavenItemSlot.Head,
		source: "Prosperity 3",
		spent: true,
		desc: "During your turn, perform \"Heal ^heal^ 1, Self\" action.",
		unlockProsperity: 3,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 3,
		imageNumber: 4,

	},
	{
		id: 25,
		name: "Jagged Sword",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.OneHand,
		source: "Prosperity 3",
		spent: true,
		desc: "During your melee attack, add WOUND $wound$ to a single attack.",
		unlockProsperity: 3,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 3,
		imageNumber: 6,
	},
	{
		id: 26,
		name: "Long Spear",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Prosperity 3",
		spent: true,
		desc: "Turn a single-target melee attack into the following: *line_0_1_1*",
		unlockProsperity: 3,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 3,
		imageNumber: 8,
	},
	{
		id: 27,
		name: "Major Healing Potion",
		count: 4,
		cost: 30,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 3",
		consumed: true,
		desc: "During your turn, perform a \"Heal ^heal^ 5, self\" action.",
		unlockProsperity: 3,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 3,
		imageNumber: 10,
	},
	{
		id: 28,
		name: "Moon Earring",
		count: 2,
		cost: 20,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 3",
		consumed: true,
		desc: "During your turn, Refresh ^refresh^ all of your spent items.",
		unlockProsperity: 3,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 3,
		imageNumber: 14,
	},
	{
		id: 29,
		name: "Comfortable Shoes",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.Legs,
		source: "Prosperity 4",
		desc: "Whenever you use the default bottom of an ability card, perform a \"Move ^move^ 3\" action instead of a \"Move ^move^ 2\" action.",
		unlockProsperity: 4,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 4,
		imageNumber: 0,
	},
	{
		id: 30,
		name: "Studded Leather",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.Body,
		source: "Prosperity 4",
		spent: true,
		desc: "When attacked, the attacker gains Disadvantage on the attack and you gain Shield ^shield^ 1 for the attack.",
		unlockProsperity: 4,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 4,
		imageNumber: 2,
	},
	{
		id: 31,
		name: "Hawk Helm",
		count: 2,
		cost: 20,
		slot: GloomhavenItemSlot.Head,
		source: "Prosperity 4",
		spent: true,
		desc: "During your ranged attack, add +1 Range ^range^ to your entire Attack action.",
		unlockProsperity: 4,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 4,
		imageNumber: 4,

	},
	{
		id: 32,
		name: "Tower Shield",
		count: 2,
		cost: 40,
		slot: GloomhavenItemSlot.OneHand,
		source: "Prosperity 4",
		spent: true,
		desc: "When damaged by an attack, gain Shield ^shield^ 2 for the attack.",
		unlockProsperity: 4,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 4,
		imageNumber: 6,
	},
	{
		id: 33,
		name: "Volatile Bomb",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.OneHand,
		source: "Prosperity 4",
		consumed: true,
		desc: "During your single-target ranged attack action, turn the attack into the following: *cone_1_1*",
		unlockProsperity: 4,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 4,
		imageNumber: 8,
	},
	{
		id: 34,
		name: "Major Stamina Potion",
		count: 4,
		cost: 30,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 4",
		consumed: true,
		desc: "During your turn, Recover ^recover^ up to three of your discarded cards.",
		faq: "[Errata] The item should allow you to recover only two discarded cards. This is change in an upcoming expansion but may be used in the base game.",
		unlockProsperity: 4,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 4,
		imageNumber: 10,
	},
	{
		id: 35,
		name: "Falcon Figurine",
		count: 2,
		cost: 50,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 4\nScenario #98 (Treasure #79)",
		consumed: true,
		summon: {
			hp: 2,
			move: 3,
			attack: 2,
			range: 0
		},
		desc: "Summon Jade Falcon (Flying ^flying^)",
		faq: "The card is treated like a persistent bonus, going in the active area until the summon is killed or the card is removed (removing the summon and consuming the item). If the card is refreshed and there is an active summon from the card, the active summon disappears.",
		unlockProsperity: 4,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 4,
		imageNumber: 14,
	},
	{
		id: 36,
		name: "Boots of Dashing",
		count: 2,
		cost: 40,
		slot: GloomhavenItemSlot.Legs,
		source: "Prosperity 5",
		spent: true,
		desc: "During your movement, add +3 Move ^move^ to the movement.",
		unlockProsperity: 5,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 5,
		imageNumber: 0,
	},
	{
		id: 37,
		name: "Robes of Evocation",
		count: 2,
		cost: 40,
		slot: GloomhavenItemSlot.Body,
		source: "Prosperity 5",
		spent: true,
		desc: "During your attack, @x-any@  to add +1 Attack ^attack^ to the entire Attack action.",
		unlockProsperity: 5,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 5,
		imageNumber: 2,
	},
	{
		id: 38,
		name: "Heavy Basinet",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.Head,
		source: "Prosperity 5",
		minusOneCardsAdded: 2,
		desc: "You are immune to STUN $stun$ and MUDDLE $muddle$.",
		unlockProsperity: 5,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 5,
		imageNumber: 4,
	},
	{
		id: 39,
		name: "Hooked Chain",
		count: 2,
		cost: 40,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Prosperity 5",
		spent: true,
		desc: "During your ranged attack, add PULL $pull$ 2 to the entire Attack action.",
		unlockProsperity: 5,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 5,
		imageNumber: 6,
	},
	{
		id: 40,
		name: "Versatile Dagger",
		count: 2,
		cost: 25,
		slot: GloomhavenItemSlot.OneHand,
		source: "Prosperity 5",
		desc: "Whenever you use the default top of an ability card, perform an \"Attack ^attack^ 3\" action instead of an \"Attack ^attack^ 2\" action.",
		unlockProsperity: 5,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 5,
		imageNumber: 8,
	},
	{
		id: 41,
		name: "Major Power Potion",
		count: 4,
		cost: 40,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 5\nScenario #105 (Treasure #83)",
		consumed: true,
		desc: "During your attack, add +2 Attack ^attack^ to your entire Attack action.",
		unlockProsperity: 5,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 5,
		imageNumber: 10,
	},
	{
		id: 42,
		name: "Ring of Haste",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 5",
		consumed: true,
		desc: "At the end of your turn, play one card from your hand and immediately perform the bottom action of the card.",
		unlockProsperity: 5,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 5,
		imageNumber: 14,
	},
	{
		id: 43,
		name: "Boots of Quickness",
		count: 2,
		cost: 75,
		slot: GloomhavenItemSlot.Legs,
		source: "Prosperity 6",
		spent: true,
		desc: "At the beginning of a round, after all ability cards have been revealed, increase or decrease your leading initiative value by 20.",
		unlockProsperity: 6,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 6,
		imageNumber: 0,
	},
	{
		id: 44,
		name: "Splintmail",
		count: 2,
		cost: 35,
		slot: GloomhavenItemSlot.Body,
		source: "Prosperity 6",
		minusOneCardsAdded: 4,
		desc: "On the next four sources of damage to you from attacks, gain Shield ^shield^ 1.",
		unlockProsperity: 6,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 6,
		imageNumber: 2,
	},
	{
		id: 45,
		name: "Pendant of Dark Pacts",
		count: 2,
		cost: 75,
		slot: GloomhavenItemSlot.Head,
		source: "Prosperity 6",
		consumed: true,
		desc: "During your turn, Refresh ^refresh^ two of your consumed #small# items. Gain CURSE $curse$.",
		faq: "The perk that ignores item effects does not prevent you from being cursed.",
		unlockProsperity: 6,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 6,
		imageNumber: 4,
	},
	{
		id: 46,
		name: "Spiked Shield",
		count: 2,
		cost: 40,
		slot: GloomhavenItemSlot.OneHand,
		source: "Prosperity 6",
		spent: true,
		desc: "When damaged by an attack, gain Shield ^shield^ 1 and Retaliate ^retaliate^ 2 for the attack.",
		unlockProsperity: 6,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 6,
		imageNumber: 6,
	},
	{
		id: 47,
		name: "Reaping Scythe",
		count: 2,
		cost: 40,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Prosperity 6",
		consumed: true,
		desc: "During your single-target melee attack action, turn the attack into the following:  *cleave_0_1*",
		unlockProsperity: 6,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 6,
		imageNumber: 8,
	},
	{
		id: 48,
		name: "Major Mana Potion",
		count: 4,
		cost: 30,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 6\nReward from Scenario #104",
		consumed: true,
		desc: "During your turn, create any two elements. @any@ @any@",
		unlockProsperity: 6,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 6,
		imageNumber: 10,
	},
	{
		id: 49,
		name: "Sun Earring",
		count: 2,
		cost: 40,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 6",
		consumed: true,
		desc: "During your turn, Refresh ^refresh^ all of your spent items and \"Heal ^heal^ 3, Self\" action.",
		unlockProsperity: 6,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 6,
		imageNumber: 14,
	},
	{
		id: 50,
		name: "Steel Sabatons",
		count: 2,
		cost: 60,
		slot: GloomhavenItemSlot.Legs,
		source: "Prosperity 7",
		minusOneCardsAdded: 2,
		desc: "If you move 1 or fewer hexes on your turn, gain Shield ^shield^ 1 for the round.",
		unlockProsperity: 7,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 7,
		imageNumber: 0,
	},
	{
		id: 51,
		name: "Shadow Armor",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.Body,
		source: "Prosperity 7",
		consumed: true,
		desc: "When you are damaged by an attack, suffer no damage instead.",
		unlockProsperity: 7,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 7,
		imageNumber: 2,
	},
	{
		id: 52,
		name: "Protective Charm",
		count: 2,
		cost: 60,
		slot: GloomhavenItemSlot.Head,
		source: "Prosperity 7\nReward from Scenario #109",
		desc: "You are immune to POISON $poison$ and WOUND $wound$.",
		unlockProsperity: 7,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 7,
		imageNumber: 4,
	},
	{
		id: 53,
		name: "Black Knife",
		count: 2,
		cost: 25,
		slot: GloomhavenItemSlot.OneHand,
		source: "Prosperity 7",
		spent: true,
		desc: "During your melee attack, add CURSE $curse$ to a single attack.",
		unlockProsperity: 7,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 7,
		imageNumber: 6,
	},
	{
		id: 54,
		name: "Staff of Eminence",
		count: 2,
		cost: 60,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Prosperity 7",
		spent: true,
		desc: "During your ranged attack, @x-any@ to add +1 Attack ^attack^ to the entire Attack action.",
		unlockProsperity: 7,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 7,
		imageNumber: 8,
	},
	{
		id: 55,
		name: "Super Healing Potion",
		count: 4,
		cost: 50,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 7",
		consumed: true,
		desc: "During your turn, perform a \"Heal ^heal^ 7, self\" action.",
		unlockProsperity: 7,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 7,
		imageNumber: 10,
	},
	{
		id: 56,
		name: "Ring of Brutality",
		count: 2,
		cost: 40,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 7",
		consumed: true,
		desc: "At the end of your turn, play one card from your hand and immediately perform the top action of the card.",
		unlockProsperity: 7,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 7,
		imageNumber: 14,
	},
	{
		id: 57,
		name: "Serene Sandals",
		count: 2,
		cost: 75,
		slot: GloomhavenItemSlot.Legs,
		source: "Prosperity 8",
		desc: "Whenever you use the default bottom of an ability card perform a \"Move ^move^ 4\" action instead of a \"Move ^move^ 2\" action.",
		unlockProsperity: 8,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 8,
		imageNumber: 0,
	},
	{
		id: 58,
		name: "Cloak of Phasing",
		count: 2,
		cost: 75,
		slot: GloomhavenItemSlot.Body,
		source: "Prosperity 8",
		desc: "Gain Flying ^flying^. While occupying an obstacle hex, you are considered INVISIBLE $invisible$ and cannot attack",
		unlockProsperity: 8,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 8,
		imageNumber: 2,
	},
	{
		id: 59,
		name: "Telescopic Lens",
		count: 2,
		cost: 50,
		slot: GloomhavenItemSlot.Head,
		source: "Prosperity 8\nOption from Scenario 100",
		spent: true,
		desc: "During your ranged attack, add +2 Range ^range^ to your entire Attack action",
		unlockProsperity: 8,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 8,
		imageNumber: 4,
	},
	{
		id: 60,
		name: "Unstable Explosives",
		count: 2,
		cost: 45,
		slot: GloomhavenItemSlot.OneHand,
		source: "Prosperity 8",
		consumed: true,
		desc: "Turn a single target ranged attack into the following: *cube_2_2*. All allies in the attack area suffer 3 damage.",
		unlockProsperity: 8,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 8,
		imageNumber: 6,
	},
	{
		id: 61,
		name: "Wall Shield",
		count: 2,
		cost: 60,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Prosperity 8",
		spent: true,
		desc: "When damaged by an attack, gain Shield ^shield^ 4 for the attack.",
		unlockProsperity: 8,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 8,
		imageNumber: 8,
	},
	{
		id: 62,
		name: "Doom Powder",
		count: 2,
		cost: 40,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 8",
		consumed: true,
		desc: "During your attack, add STUN $stun$, POISON $poison$, and CURSE $curse$ to a single attack.",
		unlockProsperity: 8,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 8,
		imageNumber: 10,
	},
	{
		id: 63,
		name: "Lucky Eye",
		count: 2,
		cost: 60,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 8",
		consumed: true,
		desc: "During your turn, STRENGTHEN $strengthen$ yourself and all adjacent allies.",
		unlockProsperity: 8,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 8,
		imageNumber: 12,
	},
	{
		id: 64,
		name: "Boots of Sprinting",
		count: 2,
		cost: 75,
		slot: GloomhavenItemSlot.Legs,
		source: "Prosperity 9",
		spent: true,
		desc: "During your movement, add +4 Move ^move^ to the movement.",
		unlockProsperity: 9,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 9,
		imageNumber: 0,
	},
	{
		id: 65,
		name: "Platemail",
		count: 2,
		cost: 50,
		slot: GloomhavenItemSlot.Body,
		source: "Prosperity 9",
		spent: true,
		minusOneCardsAdded: 5,
		useSlots: 5,
		desc: "On the next five sources of damage to you from attacks, gain Shield ^shield^ 1.",
		unlockProsperity: 9,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 9,
		imageNumber: 2,
	},
	{
		id: 66,
		name: "Mask of Terror",
		count: 2,
		cost: 50,
		slot: GloomhavenItemSlot.Head,
		source: "Prosperity 9\nScenario #110 (Treasure #84)",
		desc: "During your melee attack, add PUSH $push$ 1.",
		unlockProsperity: 9,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 9,
		imageNumber: 4,
	},
	{
		id: 67,
		name: "Balanced Blade",
		count: 2,
		cost: 60,
		slot: GloomhavenItemSlot.OneHand,
		source: "Prosperity 9",
		desc: "Whenever you use the default top of an ability card, perform an \"Attack ^attack^ 4\" instead of an \"Attack ^attack^ 2\" action.",
		unlockProsperity: 9,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 9,
		imageNumber: 6,
	},
	{
		id: 68,
		name: "Halberd",
		count: 2,
		cost: 60,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Prosperity 9\nScenario #111 (Treasure #92)\nSection 132 -> g106\n\"Strangler's Park\"",
		desc: "During your single target melee attack, you can attack any single enemy within 2 hexes.",
		unlockProsperity: 9,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 9,
		imageNumber: 8,
	},
	{
		id: 69,
		name: "Star Earring",
		count: 2,
		cost: 70,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 9\nTreasure #56",
		desc: "During your turn, Refresh ^refresh^ all of your spent items, \"Heal ^heal^ 3, Self\" action, and Recover ^recover^ up to two of your discarded cards.",
		consumed: true,
		unlockProsperity: 9,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 9,
		imageNumber: 10,
	},
	{
		id: 70,
		name: "Second Chance Ring",
		count: 2,
		cost: 75,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Prosperity 9\nFC Challenge Scenario, Rift Card 12 (Treasure #89)\nSection 103 -> 84\n\"Gateway to the Firmament\"",
		desc: "At the end of your turn, play two cards from your hand and perform an additional turn this round based on your new leading initiative (which must be later than your previous initiative).",
		consumed: true,
		unlockProsperity: 9,
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 9,
		imageNumber: 12,
	},
	{
		id: 71,
		name: "Boots of Levitation",
		count: 2,
		cost: 50,
		slot: GloomhavenItemSlot.Legs,
		source: "Random Item",
		desc: "Gain Flying ^flying^",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 0
	},
	{
		id: 72,
		name: "Shoes of Happiness",
		count: 2,
		cost: 50,
		slot: GloomhavenItemSlot.Legs,
		source: "Random Item",
		desc: "If you move 6 or more hexes on your turn, gain ^experience_1^.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 1
	},
	{
		id: 73,
		name: "Blinking Cape",
		count: 2,
		cost: 50,
		slot: GloomhavenItemSlot.Body,
		source: "Random Item",
		consumed: true,
		desc: "During your turn, perform a \"Move ^move^ 4, Jump ^jump^\" action",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 2
	},
	{
		id: 74,
		name: "Swordedge Armor",
		count: 2,
		cost: 40,
		slot: GloomhavenItemSlot.Body,
		source: "Random Item",
		spent: true,
		minusOneCardsAdded: 4,
		desc: "On the next three sources of damage from attacks targeting you, gain Shield ^shield^ 1, Retaliate ^retaliate^ 1",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 3
	},
	{
		id: 75,
		name: "Circlet of Elements",
		count: 2,
		cost: 25,
		slot: GloomhavenItemSlot.Head,
		source: "Random Item",
		spent: true,
		desc: "During your turn, @x-any@ to create any element. @any@",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 4
	},
	{
		id: 76,
		name: "Chain Hood",
		count: 2,
		cost: 40,
		slot: GloomhavenItemSlot.Head,
		source: "Random Item",
		minusOneCardsAdded: 1,
		desc: "While you are adjacent to three or more monsters, gain Shield ^shield^ 1",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 5
	},
	{
		id: 77,
		name: "Frigid Blade",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.OneHand,
		source: "Random Item",
		desc: "During your melee attack, @x-ice@ to add +2 Attack ^attack^ to a single attack.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 6
	},
	{
		id: 78,
		name: "Storm Blade",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.OneHand,
		source: "Random Item",
		desc: "During your melee attack, @x-wind@ to add +2 Attack ^attack^ to a single attack.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 7
	},
	{
		id: 79,
		name: "Inferno Blade",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.OneHand,
		source: "Random Item",
		desc: "During your melee attack, @x-fire@ to add +2 Attack ^attack^ to a single attack.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 8
	},
	{
		id: 80,
		name: "Tremor Blade",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.OneHand,
		source: "Random Item",
		desc: "During your melee attack, @x-earth@ to add +2 Attack ^attack^ to a single attack.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 9
	},
	{
		id: 81,
		name: "Brilliant Blade",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.OneHand,
		source: "Random Item",
		desc: "During your melee attack, @x-light@ to add +2 Attack ^attack^ to a single attack.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 10
	},
	{
		id: 82,
		name: "Night Blade",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.OneHand,
		source: "Random Item",
		desc: "During your melee attack, @x-dark@ to add +2 Attack ^attack^ to a single attack.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 11
	},
	{
		id: 83,
		name: "Wand of Frost",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.OneHand,
		source: "Random Item",
		spent: true,
		desc: "During your turn, create Ice. @ice@",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 12
	},
	{
		id: 84,
		name: "Wand of Storms",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.OneHand,
		source: "Random Item",
		spent: true,
		desc: "During your turn, create Wind. @wind@",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 13
	},
	{
		id: 85,
		name: "Wand of Infernos",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.OneHand,
		source: "Random Item",
		spent: true,
		desc: "During your turn, create Fire. @fire@",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 14
	},
	{
		id: 86,
		name: "Wand of Tremors",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.OneHand,
		source: "Random Item",
		spent: true,
		desc: "During your turn, create Earth. @earth@",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 15
	},
	{
		id: 87,
		name: "Wand of Brilliance",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.OneHand,
		source: "Random Item",
		spent: true,
		desc: "During your turn, create Light. @light@",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 16
	},
	{
		id: 88,
		name: "Wand of Darkness",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.OneHand,
		source: "Random Item",
		spent: true,
		desc: "During your turn, create Dark. @dark@",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 17
	},
	{
		id: 89,
		name: "Minor Cure Potion",
		count: 2,
		cost: 10,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Random Item",
		consumed: true,
		desc: "During your turn, remove one negative condition on yourself. This can be used while you have STUN $stun$.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 18
	},
	{
		id: 90,
		name: "Major Cure Potion",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Random Item\nScenario #102 (Treasure #77)",
		consumed: true,
		desc: "During your turn, remove all negative conditions on yourself. This can be used while you have STUN $stun$.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 19
	},
	{
		id: 91,
		name: "Steel Ring",
		count: 2,
		cost: 20,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Random Item",
		consumed: true,
		desc: "When damaged by an attack targeting you, gain Shield ^shield^ 4 for the attack.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 20
	},
	{
		id: 92,
		name: "Dampening Ring",
		count: 2,
		cost: 25,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Random Item",
		consumed: true,
		desc: "Before an enemy would consume an element, consume that element instead for no effect",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 21
	},
	{
		id: 93,
		name: "Scroll of Power",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Random Item",
		consumed: true,
		desc: "During an ally's attack, add +1 Attack ^attack^ to their entire attack action",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 22
	},
	{
		id: 94,
		name: "Scroll of Healing",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Random Item",
		consumed: true,
		desc: "During your turn, perform a \"Heal ^heal^ 3, Range ^range^ 5\" action",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 23,
	},
	{
		id: 95,
		name: "Scroll of Stamina",
		count: 2,
		cost: 50,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Random Item",
		consumed: true,
		desc: "During your turn, an ally within Range ^range^ 5 may Recover ^recover^ up to two of their discarded cards",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 10,
		imageNumber: 24,
	},
	{
		id: 96,
		name: "Rocket Boots",
		count: 2,
		cost: 80,
		slot: GloomhavenItemSlot.Legs,
		source: "Scenario #66 (Treasure #36)",
		spent: true,
		desc: "During your movement, add +3 Move ^move^ and Jump ^jump^ to a single movement",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 0
	},
	{
		id: 97,
		name: "Endurance Footwraps",
		count: 1,
		cost: 40,
		slot: GloomhavenItemSlot.Legs,
		source: "Scenario #38 (Treasure #29)",
		desc: "If you move 4 or more hexes on your turn, perform a \"\"Heal ^heal^ 1, Self\"\" action.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 2
	},
	{
		id: 98,
		name: "Drakescale Boots",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.Legs,
		source: "Scenario #43 (Treasure #35)",
		desc: "You are unaffected by difficult and hazardous terrain.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 3
	},
	{
		id: 99,
		name: "Magma Waders",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.Legs,
		source: "Scenario #63 (Treasure #12)",
		desc: "Ignore the damaging effects of hazardous terrain and perform a \"Heal ^heal^ 2, Self\" action on any turn in which you have entered a hazardous terrain hex.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 4
	},
	{
		id: 100,
		name: "Robes of Summoning",
		count: 1,
		cost: 40,
		slot: GloomhavenItemSlot.Body,
		source: "Scenario #31 (Treasure #69)",
		spent: true,
		desc: "During your turn, perform a \"Heal ^heal^ 2, target any summoned ally\" action.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 5
	},
	{
		id: 101,
		name: "Second Skin",
		count: 1,
		cost: 30,
		slot: GloomhavenItemSlot.Body,
		source: "Scenario #06 (Treasure #50)",
		desc: "Remove two ^modifier_minus_one_circle^ from your attack modifier deck.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 6
	},
	{
		id: 102,
		name: "Sacrificial Robes",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.Body,
		source: "City Event 40",
		spent: true,
		desc: "During your ranged attack, suffer 3 damage to add +1 Attack ^attack^ to the entire Attack action.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 7
	},
	{
		id: 103,
		name: "Drakescale Armor",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.Body,
		source: "Scenario #34 (Treasure #23)",
		desc: "You are immune to POISON $poison$ and WOUND $wound$.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 8
	},
	{
		id: 104,
		name: "Steam Armor",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.Body,
		source: "Scenario #40 (Treasure #47)",
		consumed: true,
		desc: "On the next five sources of damage from attacks targeting you, gain Shield ^shield^ 1.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 9
	},
	{
		id: 105,
		name: "Flea-Bitten Shawl",
		count: 1,
		cost: 10,
		slot: GloomhavenItemSlot.Body,
		source: "City Event 30",
		desc: "You are considered to have an initiative of 99 for the purpose of enemy focusing.",
		faq: "The item does not actually change a character's initiative so it doesn't affect their summons' initiative. It only changes how monster's treat the character during focus evaluation.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 10
	},
	{
		id: 106,
		name: "Necklace of Teeth",
		count: 1,
		cost: 40,
		slot: GloomhavenItemSlot.Head,
		source: "Road Event 05",
		desc: "Any time you kill an enemy during your turn, perform a \"Heal ^heal^ 1, Self\" action.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 11
	},
	{
		id: 107,
		name: "Horned Helm",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.Head,
		source: "Scenario #03 (Treasure #65)",
		desc: "After moving 4 or more hexes on your turn, add +1 Attack ^attack^ to your next melee attack this turn.",
		faq: "This bonus must be used on the turn it is gained. It cannot be saved. If you perform multiple move abilities, you may use the item as long as you have moved a total of at least 4 hexes. The item can only be used once during your turn even if you move 4 hexes multiple times during your turn.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 12
	},
	{
		id: 108,
		name: "Drakescale Helm",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.Head,
		source: "Scenario #25 (Treasure #58)",
		desc: "Whenever you gain MUDDLE $muddle$, gain STRENGTHEN $strengthen$ instead.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 14
	},
	{
		id: 109,
		name: "Thief's Hood",
		count: 1,
		cost: 20,
		slot: GloomhavenItemSlot.Head,
		source: "City Event 62",
		consumed: true,
		desc: "During your \"Loot ^loot^ 1\" ability, perform a \"Loot ^loot^ 2\" ability instead.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 15
	},
	{
		id: 110,
		name: "Helm of the Mountain",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.Head,
		source: "Scenario #82 (Treasure #62)",
		desc: "When attacked, if @earth@ is Strong, IMMOBILIZE $immobilize$ the attacker.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 16
	},
	{
		id: 111,
		name: "Wave Crest",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.Head,
		source: "Scenario #64 (Treasure #09)",
		desc: "When attacked, if @ice@ is Strong, perform a \"PUSH $push$ 2\" action targeting the attacker.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 17
	},
	{
		id: 112,
		name: "Ancient Drill",
		count: 2,
		cost: 30,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Reward From Scenario #65\nOption from Scenario 100",
		consumed: true,
		desc: "During your melee attack, add +2 Attack ^attack^ and PIERCE $pierce$ 2 to the entire Attack action",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 18
	},
	{
		id: 113,
		name: "Skullbane Axe",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Reward From Scenario #11\nReward From Scenario #12",
		spent: true,
		desc: "During your melee attack targeting a Living Corpse, Living Spirit, or Living Bones, add +5 Attack ^attack^ to a single attack.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 20
	},
	{
		id: 114,
		name: "Staff of Xorn",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Reward from Scenario #53",
		consumed: true,
		desc: "During your ranged attack, add POISON $poison$ and MUDDLE $muddle$ to the entire Attack action",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 21
	},
	{
		id: 115,
		name: "Mountain Hammer",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Scenario #82 (Treasure #62)",
		consumed: true,
		summon: {
			hp: 4,
			move: 1,
			attack: 3,
			range: 0
		},
		desc: "Summon Warrior Spirit",
		faq: "The card is treated like a persistent bonus, going in the active area until the summon is killed or the card is removed (removing the summon and consuming the item). If the card is refreshed and there is an active summon from the card, the active summon disappears.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 22
	},
	{
		id: 116,
		name: "Fueled Falchion",
		count: 2,
		cost: 20,
		slot: GloomhavenItemSlot.OneHand,
		source: "Scenario #23 (Treasure #72)",
		consumed: true,
		desc: "During your single-target melee attack, the target and all enemies adjacent to the target suffer 1 damage",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 23
	},
	{
		id: 117,
		name: "Bloody Axe",
		count: 2,
		cost: 40,
		slot: GloomhavenItemSlot.OneHand,
		source: "City Event 53\nRoad Event 53",
		spent: true,
		desc: "During your melee attack, suffer 2 damage to add +1 Attack ^attack^ to the entire Attack action.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 25
	},
	{
		id: 118,
		name: "Staff of Elements",
		count: 2,
		cost: 50,
		slot: GloomhavenItemSlot.TwoHands,
		source: "City Event 57",
		spent: true,
		desc: "During your turn, create any element. @any@",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 27
	},
	{
		id: 119,
		name: "Skull of Hatred",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.OneHand,
		source: "Reward From Scenario #95",
		consumed: true,
		desc: "During your turn, CURSE $curse$ all adjacent enemies.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 29
	},
	{
		id: 120,
		name: "Staff of Summoning",
		count: 1,
		cost: 60,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Reward From Scenario #88",
		spent: true,
		desc: "During your turn, a summoned ally within Range ^range^ 3 performs a \"Move ^move^ 3\" action with you controlling the action.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 30
	},
	{
		id: 121,
		name: "Orb of Dawn",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.OneHand,
		source: "Reward From Scenario #85",
		desc: "During your turn, @x-dark@ to create Light. @light@",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 31
	},
	{
		id: 122,
		name: "Orb of Twilight",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.OneHand,
		source: "Scenario #89 (Treasure #27)",
		desc: "During your turn, @x-light@ to create Dark. @dark@",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 32
	},
	{
		id: 123,
		name: "Ring of Skulls",
		count: 2,
		cost: 50,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Scenario #04 (Treasure #38)",
		consumed: true,
		summon: {
			hp: 3,
			move: 2,
			attack: 2,
			range: 0
		},
		desc: "SummonSkeleton",
		faq: "The card is treated like a persistent bonus, going in the active area until the summon is killed or the card is removed (removing the summon and consuming the item). If the card is refreshed and there is an active summon from the card, the active summon disappears.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 33
	},
	{
		id: 124,
		name: "Doomed Compass",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Scenario #93 (Treasure #54)",
		consumed: true,
		desc: "During your turn, force an enemy within Range ^range^ 5 to perform a \"Move ^move^ 2\" action with you controlling the action.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 35
	},
	{
		id: 125,
		name: "Curious Gear",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.SmallItem,
		source: "City Event 03\nOption from Scenario 100",
		consumed: true,
		desc: "During your turn, disarm all traps within Range ^range^ 2.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 36
	},
	{
		id: 126,
		name: "Remote Spider",
		count: 1,
		cost: 40,
		slot: GloomhavenItemSlot.SmallItem,
		source: "City Event 43\nOption from Scenario 100",
		consumed: true,
		desc: "During your turn, POISON $poison$ all adjacent enemies.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 37
	},
	{
		id: 127,
		name: "Giant Remote Spider",
		count: 1,
		cost: 60,
		slot: GloomhavenItemSlot.SmallItem,
		source: "City Event 61",
		consumed: true,
		desc: "During your turn, perform a \"Loot ^loot^ 1\" action.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 38
	},
	{
		id: 128,
		name: "Black Censer",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Reward From Scenario #90",
		consumed: true,
		desc: "During your turn, MUDDLE $muddle$ all enemies with Range ^range^ 2.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 39
	},
	{
		id: 129,
		name: "Black Card",
		count: 1,
		cost: 75,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Road Event 51",
		consumed: true,
		desc: "During your turn, place a character token on an adjacent normal or elite enemy. You add +1 Attack ^attack^ to all your attacks targeting this enemy.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 40
	},
	{
		id: 130,
		name: "Helix Ring",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Scenario #81 (Treasure #68)",
		consumed: true,
		desc: "During your turn, @x-light@ @x-dark@ to perform a \"Heal ^heal^ 25, Self\" action",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 41
	},
	{
		id: 131,
		name: "Heart of the Betrayer",
		count: 1,
		cost: 60,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Scenario #79 (Treasure #52)",
		consumed: true,
		desc: "When attacked by an adjacent normal enemy, force the enemy to attack one of its allies within its range instead.",
		faq: "This item cannot be used if there is no other enemy in range to be attacked.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 42
	},
	{
		id: 132,
		name: "Power Core",
		count: 1,
		cost: 75,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Scenario #67",
		consumed: true,
		summon: {
			hp: 5,
			move: 2,
			attack: 3,
			range: 0
		},
		desc: "Summon Steel Construct.",
		faq: "The card is treated like a persistent bonus, going in the active area until the summon is killed or the card is removed (removing the summon and consuming the item). If the card is refreshed and there is an active summon from the card, the active summon disappears.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 43
	},
	{
		id: 133,
		name: "Resonant Crystal",
		count: 1,
		cost: 20,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Scenario #84",
		consumed: true,
		desc: "During your turn, destroy an adjacent obstacle.",
		gameType: GameType.Gloomhaven2e,
		imgFileNumber: 11,
		imageNumber: 44
	},
	{
		id: 134,
		name: "Imposing Blade",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.OneHand,
		source: "Reward from Solo Scenario #01 — {BR}",
		desc: "Any time you kill an enemy during your turn, gain Shield ^shield^ 1 for the rest of the round.",
		soloItem: GHClasses.BR,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 0
	},
	{
		id: 135,
		name: "Focusing Ray",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.OneHand,
		source: "Reward from Solo Scenario #02 — {TI}",
		consumed: true,
		desc: "During your Heal action, double the value of the Heal.",
		soloItem: GHClasses.TI,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 1
	},
	{
		id: 136,
		name: "Volatile Elixir",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Reward from Solo Scenario #03 — {SW}",
		consumed: true,
		desc: "During your ranged attack, add +2 Attack ^attack^ and gain Advantage on the entire Attack action, but suffer 2 damage for each attack made.",
		soloItem: GHClasses.SW,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 2
	},
	{
		id: 137,
		name: "Silent Stiletto",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.OneHand,
		source: "Reward from Solo Scenario #04 — {SC}",
		desc: "Any time you perform a melee attack, add PIERCE $pierce$ 1 to the Attack.",
		soloItem: GHClasses.SC,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 3
	},
	{
		id: 138,
		name: "Stone Charm",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.Head,
		source: "Reward from Solo Scenario #05 — {CH}",
		spent: true,
		desc: "During your action where an obstacle is created, create one additional obstacle and apply all effects of the action to it.",
		soloItem: GHClasses.CH,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 4
	},
	{
		id: 139,
		name: "Psychic Knife",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.OneHand,
		source: "Reward from Solo Scenario #06 — {MT}",
		desc: "Any time you perform an %Augment% action, add +1 Attack ^attack^ to the entire action.",
		soloItem: GHClasses.MT,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 5
	},
	{
		id: 140,
		name: "Sun Shield",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.OneHand,
		source: "Reward from Solo Scenario #07 — {SK}",
		desc: "When damaged by an attack, you may @x-light@ to gain Shield ^shield^ 3 for the attack.",
		soloItem: GHClasses.SK,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 6
	},
	{
		id: 141,
		name: "Utility Belt",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Reward from Solo Scenario #09 — {QM}",
		consumed: true,
		desc: "During your turn, you or any one ally may Refresh ^refresh^ one of your spent or consumed items.",
		faq: "This item cannot be refreshed.",
		soloItem: GHClasses.QM,
		lost: true,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 7
	},
	{
		id: 142,
		name: "Phasing Idol",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Reward from Solo Scenario #10 — {SU}",
		consumed: true,
		desc: "When a summon you own is damaged by an attack, it suffers no damage instead.",
		soloItem: GHClasses.SU,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 8
	},
	{
		id: 143,
		name: "Smoke Elixir",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.SmallItem,
		source: "Reward from Solo Scenario #11 — {NS}",
		consumed: true,
		desc: "During your turn, gain INVISIBLE $invisible$ and create dark. @dark@",
		soloItem: GHClasses.NS,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 9
	},
	{
		id: 144,
		name: "Pendant of the Plague",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.Head,
		source: "Reward from Solo Scenario #12 — {PH}",
		spent: true,
		desc: "During your turn, POISON $poison$ and CURSE $curse$ one enemy within Range ^range^ 3.",
		soloItem: GHClasses.PH,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 10
	},
	{
		id: 145,
		name: "Mask of Death",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.Head,
		source: "Reward from Solo Scenario #08 — {BE}",
		desc: "Any time you perform a melee attack and you have exactly 1 hit point, add +2 Attack ^attack^ to the Attack.",
		soloItem: GHClasses.BE,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 11
	},
	{
		id: 146,
		name: "Master's Lute",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Reward from Solo Scenario #13 — {SS}",
		desc: "After performing any %song% action, immediately perform an Attack ^attack^ 2 or Move ^move^ 2 action.",
		soloItem: GHClasses.SS,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 12
	},
	{
		id: 147,
		name: "Cloak of the Hunter",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.Body,
		source: "Reward from Solo Scenario #14 — {DS}",
		desc: "Any time you perform a %Doom% action, MUDDLE $muddle$ the target of the %Doom%.",
		soloItem: GHClasses.DS,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 13
	},
	{
		id: 148,
		name: "Doctor's Coat",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.Body,
		source: "Reward from Solo Scenario #15 — {SB}",
		desc: "Any time an ally performs a Medical Pack or Large Medical Pack action, they add +1 Heal ^heal^ to their Heal.",
		soloItem: GHClasses.SB,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 14
	},
	{
		id: 149,
		name: "Elemental Boots",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.Legs,
		source: "Reward from Solo Scenario #16 — {EL}",
		spent: true,
		desc: "If you move 5 or more hexes on your turn, create any element. @any@",
		soloItem: GHClasses.EL,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 15
	},
	{
		id: 150,
		name: "Staff of Command",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.TwoHands,
		source: "Reward from Solo Scenario #17 — {BT}",
		spent: true,
		desc: "After performing a %Command% action, play one card from your hand and immediately perform the same side of the card (top or bottom) as the %Command% action.",
		soloItem: GHClasses.BT,
		gameType: Expansions.GH2eSoloScenarios,
		imgFileNumber: 1,
		imageNumber: 16
	},
	{
		id: 151,
		name: "Sword of the Sands",
		count: 1,
		cost: 50,
		slot: GloomhavenItemSlot.OneHand,
		source: "Reward from Solo Scenario #18 — {XX}",
		consumed: true,
		desc: "During your melee attack, add POISON $poison$ and WOUND $wound$ to the entire action.",
		soloItem: GHClasses.XX,
		gameType: Expansions.GH2eSoloScenarios,
		specialUnlock: SpecialUnlockTypes.EnvelopeX,
		imgFileNumber: 1,
		imageNumber: 17
	},
]
